<!--
Wirtten by Chen,Qian ID:27867808
-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Product</title>

  <!-- favicon -->
  <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
  <link rel="manifest" href="/favicon/site.webmanifest">
  <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
  <link rel="shortcut icon" href="/favicon/favicon.ico">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-config" content="/favicon/browserconfig.xml">
  <meta name="theme-color" content="#ffffff">
  
  <!-- css -->
    <link rel="stylesheet" href="./css/backStoreProduct_7808.css" />
    <link rel="stylesheet" href="./css/backStoreProduct_7808_media.css"/>
  </head>
  <body>
    <!--header-->
    <header>
      <figure class="logo">
        <a href="Index_5067.html">  <img
          src="./img/default.png"
          alt="Logo is here"
          class="logo"
        /></a>
      </figure>

      <figure class="user">
        <img src="./img/userIcon.png" alt="userLogo" class="userIcon" /><br />
        <p>User</p>
      </figure>
    </header>

    <section class="container">
      <!--    left panner-->
      <div class="banner">
        <a href="./backStore_7808.html">Products</a>
        <a href="./Users_9518.html">Users</a>
        <a href="./backOrder_40054003.html">Orders</a>
        <!-- <a href="#"></a>
        <a href="#"></a>
        <a href="#"></a>
        <a href="#"></a>
        <a href="#"></a>
        <a href="#"></a> -->
      </div>
	  
      <!-- product List -->
      <div class="productList">
		  <?php
		  	$index=$_GET["index"];
		  	if($index!=0){
		  		$fp=file("products.txt")[$index-1]; 
		  	    $s_arr = preg_split("/:/",$fp);
		  	}
		  ?>
		  <form method="post" action="/A3/Padd_7808.php?index="<?php 
				echo $index;
				?>">
				
        <table class="list" id="form">
			<td style="display: none;">
			    <input type="index" name="index" required="required" value="<?php 
				   echo $index;
				?>">
			</td>
          <!-- first row -->
          <tr class="row">
            <td>Product Item#:</td>
            <td>
              <?php
              	if($index!=0)
					echo $index;
				else
					echo "GENERATED BY SYSTEM"
              	?>
            </td>
              
            <!-- <td>
              20%<input type="radio" name="discount" /> 
              
            </td> -->
          </tr>

          <!-- second row -->
          <tr class="row">
            <td>Product Name:</td>
             <td><input type="text" name="name" required="required"  value="<?php 
				if($index!=0)
				   echo $s_arr[1];
				?>"></td>
			 </tr>
				 <tr class="row"> <td>Product Category:</td>
            <td>
				
              <select name="type" id="type">
                <option >dg</option>
                <option selected="selected" >ft</option>
                <option >vg</option>
                <option >bk</option>
                <option >mt</option>
                <option >fs</option>
              </select>
            </td> 

          </tr>

          <!-- third row -->
          <tr class="row">
            <td>Product Inventory:</td>
            <td>
              <input type="text" name="inventory" required="required" value="<?php 
				if($index!=0)
				   echo $s_arr[2];
				?>">
            </td>
          </tr>

          <!-- fourth row -->
          <tr class="row">
            <td>Product Price:</td>
            <td><input type="text" name="price" required="required" value="<?php 
				if($index!=0)
				   echo $s_arr[3];
				?>"></td>
          </tr>

          <!-- fifth row -->
          <!-- <tr class="row">
            <td>Product description:</td>
            <td>
              <textarea name="desc" id="desc" cols="30" rows="8"></textarea>
            </td>
          </tr> -->

         
        </table>
        <button type="submit"  id="update">Save</button>
		</form>
        <footer id="footer">
          <p>
            About us | Contact us | Download app
            <br />
            Copyright © 2021 - 2025 One Mall All Rights Reserved
          </p>
        </footer>
      </div>
    </section>
    <script src="./js/jquery-1.8.3.min.js"></script>
    <script src="./js/product_7808.js"></script>
  </body>
</html>
